# TouchDesigner automation helper configuration.
# Values act as defaults and can be overridden per project component.

logging:
  base_dir: logs
  osc_history_file: logs/osc_history.log
  osc_max_lines: 200
  textport_file: logs/textport.log
  textport_max_lines: 500
  midi_in_file: logs/midi_in.log
  midi_out_file: logs/midi_out.log
  rotation_bytes: 2097152  # 2 MiB

midi:
  default_input_device: midicraft
  default_output_device: eos
